name: thinkcreative_technologies #changing it will force you to change appname in import statement inside every .dart file.
description: Admin app for Mobijet - Customer Support & Agents Management App

version: 1.0.16+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # ---------- 69 direct dependencies last updated on 08/28/2023, 03:32 PM--------------
  extended_image: ^8.2.0
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  ffmpeg_kit_flutter_new: ^4.1.0
  flutter_launcher_plus: 0.0.6
  font_awesome_flutter: ^10.7.0
  image_editor: ^1.6.0

  logger: ^2.6.2
  firebase_core: ^4.4.0
  camera: ^0.11.3+1
  styled_text: ^9.0.0
  cloud_firestore: ^6.1.2
  path_provider: ^2.1.2
  flutter_linkify: 6.0.0
  device_info_plus: ^12.3.0

  firebase_auth: ^6.1.4
  http: 1.1.0
  intl: ^0.20.0
  permission_handler: ^12.0.1
  video_player: ^2.8.3
  url_launcher: ^6.2.5
  media_info: 0.12.0+2
  video_editor: 3.0.0
  holding_gesture: 1.2.0
  wechat_assets_picker: ^10.1.0
  flutter_expanded_tile: ^0.3.7
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  chewie: ^1.7.5
  connectivity_plus: ^5.0.2
  http_auth: ^1.0.4
  flutter_cached_pdfview: ^0.4.3
  firebase_messaging: ^16.1.1
  file_picker: ^10.3.10
  firebase_storage: ^13.0.6
  jiffy: ^6.4.4
  eva_icons_flutter: 3.1.0
  page_transition: ^2.1.0
  flutter_rating_bar: 4.0.1
  percent_indicator: ^4.2.5
  provider: ^6.1.2
  pinch_zoom: ^2.0.0
  oktoast: ^3.4.0
  circular_countdown_timer: ^0.2.4
  animated_custom_dropdown: ^3.0.0
  flutter_datetime_picker: 1.5.1
  photo_view: ^0.15.0

  open_file_plus: ^3.4.1+1
  ntp: 2.0.0
  bubble_tab_indicator: 0.1.6
  random_string: 2.3.1
  # flutter_native_timezone: 2.0.0
  package_info: 2.0.2
  flag: ^7.0.0
  gallery_saver: 2.3.2
  omni_datetime_picker: ^2.3.1
  flutter_sound: ^9.30.0
  link_preview_generator: 1.2.0
  input_slider: 0.3.1
  universal_platform: ^1.1.0
  file_saver: ^0.3.1
  dotted_border: ^3.1.0
  flutter_video_info: ^1.3.3
  share: 2.0.4
  flutter_switch: 0.3.2
  cupertino_icons: ^1.0.6
  excel: ^4.0.2
  intl_phone_field: ^3.2.0
  line_awesome_flutter: ^2.0.0
  # ---------- end of direct dependencies --------------
  # flutter sdk ---------
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dependency_overrides:
  http: "0.13.4"
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/RESKIN_ITEMS/appicon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/COMMON_ASSETS/
    - assets/RESKIN_ITEMS/
    - assets/flags/
    - lib/Localization/json_languages/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
    - family: PPoppins-Light
      fonts:
        - asset: fonts/Poppins/Poppins-Light.ttf
